local _, GraalHelper = ...

GraalHelper.defaults = {
    steal = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = -170,
        y = 200,
        scale = 1.0,
        active = true,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "RaidWarning",
    },

    kick = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = -170,
        y = 200,
        scale = 1.0,
        active = true,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "MapPing",
        minDuration = 1.5
    },

    hunterPackAspect = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        active = true,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
    },

    reflect = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        active = true,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
    },

    dispel = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        active = true,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
    },

    silence = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        active = true,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
        chatEnabled = true,
        chat = "PARTY",
    },

    stun = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        active = true,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
        chatEnabled = true,
        chat = "PARTY",
    },

    root = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        active = true,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
        chatEnabled = true,
        chat = "PARTY",
    },

    disarm = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        active = true,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
        chatEnabled = true,
        chat = "PARTY",
    },

    fear = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        active = true,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
        chatEnabled = true,
        chat = "PARTY",
    },

    missNotifier = {
        active = true,
        chatEnabled = true,
        chat = "PARTY",
    },

    summonNotifier = {
        active = true,
    },


    trackedSpells = {},
    spellFilter = {},
}
