local _, GraalHelper = ...

GraalHelper.defaults = {
    steal = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = -170,
        y = 200,
        scale = 1.0,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "RaidWarning",
    },

    reflect = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
    },

    silence = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
        say = true,
    },

    stun = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
        say = true,
    },

    root = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
        say = true,
    },

    disarm = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
        say = true,
    },

    fear = {
        point = "CENTER",
        relativePoint = "CENTER",
        x = 170,
        y = 200,
        scale = 1.0,
        locked = false,
        showBuffNames = true,
        displayDuration = 4,
        soundEnabled = true,
        sound = "Warning",
        say = true,
    },

    trackedSpells = {},
    spellFilter = {},
}
